name: backend ci

on:
    push:
        branches:
            - deploy
        paths:
            - '.github/workflows/bend-ci.yml'
            - 'backend/*'

defaults:
    run:
        shell: bash
        working-directory: backend

jobs:
    testcases-build:
        runs-on: ${{ vars.RUNS_ON }}
        steps:
            - name: checkout to branch
              uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'
                  cache: maven
            - name: run testcases
              run: mvn test
            - name: Build with Maven
              run: mvn clean package --file pom.xml

    docker-image:
        runs-on: ${{ vars.RUNS_On }}
        steps:
            - name: checkout to branch
              uses: actions/checkout@v3
            - name: push docker image
              run: |
                docker build -t ghcr.io/test-organization-package/frontend:latest .&&
                docker push ghcr.io/test-organization-package/frontend:latest
