name: frontend ci

on:
  pull_request:
    branches:
      - deploy
    paths:
      - '.github/workflows/bend-ci.yml'
      - 'frontend/**'

defaults:
    run:
        shell: bash
        working-directory: frontend


jobs:
    build:
        runs-on: ${{ vars.RUNS_ON }}
        steps:
            - name: checkout to the repository
              uses: actions/checkout@v3
            
            - name: setup node
              uses: actions/setup-node@v2
              with:
                node-version: 14
            
            - name: install dependencies
              run: npm install

            - name: run build
              run: npm run build

    docker-image:
        needs: build
        runs-on: ${{ vars.RUNS_On }}
        steps:
            - name: checkout to branch
              uses: actions/checkout@v3
            - name: push docker image
              run: |
                docker build -t ghcr.io/test-organization-package/frontend:latest . &&
                echo "${{ secrets.PACKAGE_TOKEN }}" | docker login ghcr.io --username "${{ vars.GIT_USERNAME }}" --password-stdin &&
                docker push ghcr.io/test-organization-package/frontend:latest

              