name: frontend backend cd

on:
  push:
    branches:
      - deploy
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to SSH and Run Docker Images
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.DNS_NAME }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
         ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} ' \
         docker stop frontend || true && \
         docker rm frontend || true && \
         docker pull ghcr.io/test-organization-package/frontend:latest && \
         docker run --name "frontend" -p 80:80 ghcr.io/test-organization-package/frontend:latest'
        